[package]
name = "file_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4"
derive_builder = "^0.12"
walkdir = "2.4.0"
hasher = { path = "../hasher" }
