version: '3.9'

services:
  opensearch:
    image: opensearchproject/opensearch:2.18.0
    env_file:
      - .env.production
    environment:
      - discovery.type=single-node
      - OPENSEARCH_URL=https://localhost:9300
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_DEFAULT_INDEX=common-folder
      - OPENSEARCH_PASSWORD=admin
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    ports:
      - "9300:9300"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - data-net

  dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:2.18.0
    restart: unless-stopped
    ports:
      - "5601:5601"
    expose:
      - '5601'
    environment:
      OPENSEARCH_HOSTS: '["https://localhost:9200"]'
      OPENSEARCH_USERNAME: 'admin'
    networks:
      - data-net
    depends_on:
      - opensearch

  cacher:
    image: redis:latest
    restart: on-failure
    environment:
      REDIS_USER: 'redis'
      REDIS_PASSWORD: 'redis'
      REDIS_USER_PASSWORD: 'redis'
    ports:
      - '6379:6379'
    volumes:
      - 'cacher-vol-1:/data/cacher'

volumes:
  es-vol-1:
    driver: local
  cacher-vol-1:
    driver: local

