version: '3.9'

services:
  opensearch:
    image: opensearchproject/opensearch:2.18.0
    restart: unless-stopped
    networks:
      - doc-searcher-net
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_URL=https://0.0.0.0:9200
      - OPENSEARCH_DEFAULT_INDEX=common-folder
      - OPENSEARCH_USERNAME=admin
      # TODO: set secure password
      - OPENSEARCH_PASSWORD=admin
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    volumes:
      - 'opensearch-vol-1:/usr/share/opensearch/data'

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.18.0
    restart: unless-stopped
    depends_on:
      - opensearch
    networks:
      - doc-searcher-net
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      OPENSEARCH_USERNAME: 'admin'
      OPENSEARCH_PASSWORD: 'admin'

  cacher:
    image: redis:latest
    restart: on-failure
    networks:
      - doc-searcher-net
    ports:
      - '6379:6379'
    volumes:
      - 'cacher-vol-1:/data/cacher'
    environment:
      REDIS_USER: 'redis'
      REDIS_PASSWORD: 'redis'
      REDIS_USER_PASSWORD: 'redis'

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    networks:
      - doc-searcher-net
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '14268:14268'
      - '4317:4317'
      - '14250:14250'
      - '4318:4318'
      - '16686:16686'

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    networks:
      - doc-searcher-net
    ports:
      - '3100:3100'

networks:
  doc-searcher-net:
    name: doc-searcher-net
    driver: bridge

volumes:
  opensearch-vol-1:
    driver: local
  cacher-vol-1:
    driver: local
