[package]
name = "elquery"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0.4", features = ["rustc-serialize", "serde"] }
derive_builder = "^0.12"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

[[test]]
name = "elquery_tests"
path = "test/test.rs"
