global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'doc-searcher'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'doc-searcher'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['doc-searcher:2892']
