[package]
name = "datetime"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0.4", features = ["rustc-serialize", "serde"] }
serde = "~1"
serde_derive = "^1.0"
serde_json = "~1"

[[test]]
name = "datetime_tests"
path = "test/test.rs"
