[package]
name = "datetime"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.218"
serde_derive = "1.0.218"
serde_json = "1.0.139"

[dependencies.chrono]
version = "0.4.37"
features = ["rustc-serialize", "serde"]

[[test]]
name = "datetime_tests"
path = "test/test.rs"
