[logger]
level = "debug"

[server]
address = "0.0.0.0"
port = 2892
workers_num = 6
enabled_tls = "false"

[cors]
methods = "GET,POST,PUT,DELETE,OPTIONS"
allowed = "*"
max_age = 3600

[elastic]
address = "localhost:9200"
username = "elastic"
password = "elastic"
enabled_tls = "false"

[cacher]
address = "localhost:6379"
username = "cacher"
password = "cacher"
expired = 3600

[embeddings]
address = "localhost:8085"
is_truncate = "false"
is_normalize = "false"
enabled_tls = "false"
