kind: pipeline
type: docker
name: doc-search-ci

environment:
  RUSTUP_VERSION: 1.90
  CARGO_BUILD_FEATURES: --all-features

steps:
  - name: cache-built-rust
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /usr/local/cargo
        - /drone/src/target
    volumes:
      - name: rust-targets
        path: /cache

  - name: build
    image: rust:1.90
    depends_on:
      - cache-built-rust
    commands:
      - rustup component add rustfmt
      - rustup component add clippy
      - cargo build --all-targets ${CARGO_BUILD_FEATURES}
    volumes:
      - name: rust-targets
        path: /cache

  - name: check
    image: rust:1.90
    depends_on:
      - build
    commands:
      - cargo check --all-targets ${CARGO_BUILD_FEATURES}
    volumes:
      - name: rust-targets
        path: /cache

  - name: fmt
    image: rust:1.90
    depends_on:
      - check
      - build
    commands:
      - rustup component add rustfmt
      - cargo fmt --all --check
    volumes:
      - name: rust-targets
        path: /cache

  - name: clippy
    image: rust:1.90
    depends_on:
      - check
      - build
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets ${CARGO_BUILD_FEATURES}
    volumes:
      - name: rust-targets
        path: /cache

  - name: test
    image: rust:1.90
    depends_on:
      - check
      - build
    commands:
      - cargo test --lib ${CARGO_BUILD_FEATURES}
    volumes:
      - name: rust-targets
        path: /cache

  - name: notify-gitea
    image: plugins/gitea-release
    settings:
      base_url: ${GITEA_SERVER}
      api_key:
        from_secret: gitea_token
      files:
        - config
        - docs
        - "*.md"
        - "bin/*"
    when:
      event: tag

volumes:
  - name: rust-targets
    temp: {}
