name: Pull Request Actions

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal

      - name: Run cargo check default features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets

      - name: Run cargo check all features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    runs-on: ubuntu-latest
    needs: [ check, fmt ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Build all targets
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets

  clippy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

  tests:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git/db
            target
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Run unit-tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib

# TODO: Added docker compose launching for tests
#  integration-tests:
#    runs-on: ubuntu-latest
#    needs: [ clippy, tests ]
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#
#      - name: Install Rust toolchain
#        uses: actions-rust-lang/setup-rust-toolchain@v1
#        with:
#          toolchain: stable
#          components: rustfmt, clippy
#          profile: minimal
#
#      - name: Cache cargo registry
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.cargo/git
#            ~/.cargo/bin
#            ~/.cargo/registry
#            ~/.cargo/git/db
#            target
#          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
#
#      - name: Run tests
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --all
