name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request_target:
    types: [ assigned, opened, synchronize ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Apt dependencies
      run: |
        sudo apt-get install -y build-essential cmake clang libclang-dev \
            llvm llvm-dev libgtk2.0-dev pkg-config libavcodec-dev \
            libavformat-dev libswscale-dev libtbb2 libtbb-dev \
            libcanberra-gtk-module libssl-dev pkg-config libjpeg-dev \
            libpng-dev libtiff-dev libopencv-dev libcanberra-gtk3-module \
            liblept5 libleptonica-dev tesseract-ocr tesseract-ocr-rus \
            libtesseract-dev automake libsdl-pango-dev libicu-dev \
            libcairo2-dev bc ssdeep
            
    - name: Build
      run: cargo build --verbose
  
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fmt
      run: cargo fmt --all --verbose
    
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --all --verbose
