name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request_target:
    types: [ assigned, opened, synchronize ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download dependencies
      run: |
        sudo apt-get install pkg-config liblept5 libleptonica-dev tesseract-ocr libtesseract-dev
    - name: Build
      run: cargo build --verbose
  
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fmt
      run: cargo fmt --all --verbose
    
  test:
    needs: [build, fmt]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --all --verbose
